#!/bin/sh
NETWORK=${NETWORK:-10.0.1.[0-9]+}
IP=$(hostname -i | egrep -o $NETWORK )
CLUSTER=${CLUSTER:-serf}
SERVICE=${SERVICE:-serf}
EVENT_HANDLER=${EVENT_HANDLER:-/etc/serf/serf_handler}
exec /usr/local/bin/serf agent -advertise="${IP}" -retry-join ${SERVICE} -join ${SERVICE} -discover=${CLUSTER} -event-handler ${EVENT_HANDLER} >>/var/log/serf.log 2>&1
